myPersonalOrgRepository/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Lightning tutorial</description>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myPersonalOrgRepository/force-app/main/default/objects/Expense__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/objects/Expense__c/fields/Reimbursed__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reimbursed?</label>
    <type>Checkbox</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/classes/ExpenseController.cls
public with sharing class ExpenseController {
    @AuraEnabled
    public static List<Expense__c> getExpenses(){
        
        return [Select id, name, client__c, Amount__c, Date__c, reimbursed__C, createdDate from Expense__c];
    } 
    
    @AuraEnabled
    public static Expense__c saveExpense(Expense__c expense) {
        // Perform isUpdateable() check here
        upsert expense;
        return expense;
        
    }
    
}