myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/OppLineItem__c.object-meta.xml
<CustomObject>
    <label>OppLineItem</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>OppLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OppLineItems</relationshipLabel>
    <relationshipName>OppLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/classes/TriggerToUpdateOpportunityHandler.cls
public class TriggerToUpdateOpportunityHandler {
    Public Account getParent(id parentId){
    	return [Select Id, name from Account where id = :parentId ];   
    }
    
    public void updateParent(list<Account> acc){
        update Acc;
    }
    
    public OppLineItem__c getFirstChild(id oppId){
       return [Select id, name__C ,opportunity__c from OppLineItem__c where opportunity__c = : oppId limit 1]; 
    }
    
    public void updateChild(List<OppLineItem__c> OppItem){
        update OppItem;
    }
        
}