myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/OppLineItem__c.object-meta.xml
<CustomObject>
    <label>OppLineItem</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>OppLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/objects/OppLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OppLineItems</relationshipLabel>
    <relationshipName>OppLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

myPersonalOrgRepository/force-app/main/default/classes/TriggerToUpdateOpportunityTest.cls
@istest(seeAllData = false)
public class TriggerToUpdateOpportunityTest {
    
     public static testMethod void getTestCoverage(){
         Account acc = new Account();
         acc.name = 'Parent Acc';
         insert acc;
         
        opportunity opp = new Opportunity();
        opp.name = 'OppTest 1';
        opp.StageName = 'Won';
        opp.CloseDate = Date.today();
        opp.AccountId = acc.Id;
        insert opp;
         
         OppLineItem__c lineItem = new OppLineItem__c();
         lineItem.name__c = 'Child 1 ';
         lineItem.Opportunity__c = opp.Id;
         insert lineItem;
        
         opp.Name = 'oppTest ';
         Test.startTest();
         update opp;
         Test.stopTest();
    }

}